export default {
	signIn: '/platform-oauth-service/user/login',
	// 走航车, 雷达信息
	tracingInfo: '/platform-grs-service/car/getHomepageTracingInfo',
	// flexpart列表信息
	flexpartDefaultSite: '/platform-grs-service/flexpart/getHomepageFlexpartDefaultSite',
	// flexpart图片请求
	getFlexpartImg: '/platform-grs-service/flexpart/getFlexpartImg',
	// 温湿气、市均值插值信息
	getTenantInterpolationLocation: '/platform-bff-data-product/homepage/general/interpolation/id',
	// 获取图层,marker信息
	// sceneLayer: '/platform-common-service/homepage/getLayer',
	// 获取全国城市
	getAllCityInfo: '/platform-bff-data-product/homepage/common/getAreaInfo',
	// 获取城市aqi
	getAqiByCity: '/platform-aqi-service/aqi/getAqiByCity',
	// 查询当天空气预报
	queryOne: '/platform-aqi-service/aqi/cityForecast/queryOne',
	// 获取全国城市站点数据
	nationSite: '/platform-bff-data-product/homepage/general/group/site/aqiAllDate',
	// 单站多因子时序分析
	singleTrendSimple: '/platform-aqi-service/aqi/singleTrendSimple',
	// 站点marker数据
	// nationSiteMarker: '/platform-aqi-service/aqi/city/getNationSiteValueByCityCode',
	nationSiteMarker: '/platform-bff-data-product/homepage/general/group/site/aqidata',
	// marker弹窗
	getAqi24HoursData: '/platform-aqi-service/aqi/city/get24HoursData',
	// 风场
	postWindy: '/platform-bff-data-product/homepage/common/windSite',
	// 获取服务城市信息
	queryDefaultCityCode: '/platform-common-service/systemConfig/queryDefaultCityCode',
	// 多站单因子时序分析
	manySitesTrendAnalysisTwo: '/platform-aqi-service/aqi/mixCity/manySitesTrendAnalysisTwo',
	// 工具箱通用搜索
	queryAttributes: '/platform-common-service/attribute/queryAttributes',
	// 预报分析
	forecastAnalysis: '/platform-aqi-service/aqi/forecast/analysis',
	// 获取管控评估卡片侧滑事件日志
	incidentLogs: '/platform-event-service/incident/sideslip/logs',
	// 研判分析卡片
	discussAnalysisCard: '/platform-aqi-service/analyze/card',
	// 研判分析卡片-饼图数据
	getToolkitFlexpartInfo: 'platform-grs-service/flexpart/getToolkitFlexpartInfo',
	// 研判分析侧滑-重点区域
	getDifferenceValue: '/platform-aqi-service/aqiStatis/getDifferenceValue',
	// 研判分析侧滑-重点行业
	keyIndustry: '/platform-aqi-service/analyze/keyIndustry',
	// 臭氧分析卡片
	ozoneAnalysisCard: '/platform-bff-data-product/homepage/general/card/analysis/ozone',
	// 臭氧分析-VOCs分析侧滑
	vocsAnalysisSlider: '/platform-bff-data-product/homepage/general/sideslip/analysis/VOCs',
	// 市级-超站信息卡片
	superstationInfo: '/platform-bff-data-product/homepage/general/card/device/getDeviceStatus',
	// 空气质量卡片
	getAirCardInfo: '/platform-bff-data-product/homepage/common/getAirCardInfo',
	// 颗粒物分析卡片
	particleAnalysisCard: '/platform-bff-data-product/homepage/general/card/analysis/particle',
	// 化学组分分析饼图接口
	chemicalRefactorList: '/platform-bff-data-product/homepage/general/side/chemicalRefactor/list',
	// 化学组分分析序列接口
	chemicalRefactorPie: '/platform-bff-data-product/homepage/general/side/chemicalRefactor/pie',
	// SPAMS分析饼图接口
	SPAMSPie: '/platform-bff-data-product/homepage/general/sideslip/particle/SPAMSPie',
	// SPAMS分析序列接口
	spamsList: '/platform-bff-data-product/homepage/general/particle/spmasList',
	// 空气质量卡片-时序分析侧滑-单站多因子时序分析
	airQualityCityData: '/platform-bff-data-product/homepage/general/sidedlip/air/cityData',
	// 空气质量卡片-时序分析侧滑-多站单因子时序分析
	airQualityNationData: '/platform-bff-data-product/homepage/general/sidedlip/air/nationData',
	// 空气质量卡片-预报分析侧滑
	airQualityCityForecastData: '/platform-bff-data-product/homepage/general/sidedlip/air/cityForecastData',
	// 空气质量卡片-区域预报侧滑
	airQualityAreaForecastPic: '/platform-bff-data-product/homepage/general/areaForecastPic',
	// 空气质量卡片-扩散条件侧滑
	airQualityForecastPic: '/platform-bff-data-product/homepage/general/airForecastPic',
	// 栅格 污染源列表
	getNearSite: '/platform-event-service/gridEvent/getNearSite',
	// 临近国控点污染信息
	getPollutions: 'platform-event-service/gridEvent/getPollutions',
	// 污染源详情
	pollutionDetail: 'platform-event-service/gridEvent/getPollutionDetail',
	// 获取走行车历史列表
	getCarHistoryList: '/platform-grs-service/car/getCarHistoryList',
	// 获取扫描雷达历史列表
	getRadarHistoryList: '/platform-bff-data-product/homepage/general/radar/time/list',
	// 获取VOCs走航车历史列表
	getVocCarHistoryList: '/platform-bff-data-product/homepage/common/car/times',
	// 获取扫描雷达数据
	getRadarData: '/platform-bff-data-product/homepage/general/scanradar/getData',
	// 获取雷达或走航车数据
	getCarVocData: '/platform-bff-data-product/homepage/common/car/voc/data',
	// 获取voc走航车因子
	getCarVocFactorAvg: '/platform-bff-data-product/homepage/common/car/voc/factorAvg',
	// 获取时间轴aqi时间序列charts
	getAqiTimeList: '/platform-bff-data-product/homepage/common/getCityTimeSeries',
	// 获取场景列表
	getUserLoginInfo: '/platform-bff-data-product/homepage/common/getUserLoginInfo',
	// 市级超站信息侧滑数据传输情况
	getTransmissionStatus: '/platform-bff-data-product/homepage/general/card/device/getNear24Online',
	// 市级超站信息侧滑数据审核情况
	getTransmissionChecked: '/platform-bff-data-product/homepage/general/card/device/getNear24Checked',
	// 筛选条件接口
	attributeAttributes: '/attribute/queryAttributes',
	// 统一图片调用接口
	downloadAttachment: '/platform-file-service/attachment/downloadAttachment',
	// 臭氧分析-大气氧化性分析
	atmoophericOx: '/platform-bff-data-product/homepage/general/sideslip/analysis/Ox',
	// 超级站站点弹窗
	supperSite: '/platform-bff-data-product/homepage/general/supperSite',
	// 超级站列表
	getSites: '/platform-bff-data-product/homepage/general/getSites',
	// 省级空气质量卡片
	getAirCardInfoProvince: '/platform-bff-data-product/homepage/common/province/getAirCardInfo',
	// VOCs相关分析卡片
	vocsAnalysisCard: '/platform-bff-data-product/homepage/general/card/analysis/vocs',
	// 大气氧化性分析卡片接口
	oxAnalysisCard: '/platform-bff-data-product/homepage/general/card/analysis/ox',
	// 获取数字字典列表
	dictionaryList: '/platform-bff-data-product/homepage/common/dictionary/list',
	// 省级-空气质量-侧滑空气质量传输分析
	airQualityDataForProvince: '/platform-bff-data-product/homepage/general/sidedlip/air/airQualityData',
	// VOCs相关性分析卡片
	analysisVOCs: '/platform-bff-data-product/homepage/general/card/analysis/vocs',
	// 省级-颗粒物-侧滑空间分布
	particleSpace: '/platform-bff-data-product/homepage/general/sidedlip/particle/space',
	// 省级-光化学分析-侧滑-空间分布
	spatialDistribution: '/platform-bff-data-product/homepage/general/airOxi/spatial/distribution',
	// 省级-空气质量-侧滑颗粒物雷达传输分析
	radarParticle: '/platform-bff-data-product/homepage/general/sidedlip/air/radar/particle',
	// 走航分析溯源
	sourceAnalysisCard: '/platform-bff-data-product/homepage/general/sailing/analysis/source',
	// 污染源企业名单excel下载
	sourceAnalysisExport: '/platform-bff-data-product/homepage/general/sailing/analysis/source/export',
	// 获取平台图片和名称
	// getLogoOrPlatformName: '/platform-baseinfo-service/config/getSysconfigValue',
	getLogoOrPlatformName: '/platform-bff-data-product/homepage/common/platform/logoAndName',
	// 颗粒物组分分析-全景图
	queryPanoramaList: '/platform-bff-data-product/homepage/general/particulate/panorama/data',
	// 收藏全景图
	collectModify: '/platform-bff-data-product/homepage/general/chart/collect/info/modify',
	// 获取全景图列表数据
	panoramaData: '/platform-bff-data-product/homepage/general/particulate/panorama/data',
	// 图表收藏
	chartCollect: '/platform-bff-data-product/homepage/general/chart/collect/info/modify'
}
